### ISSUE TITLE
Language selection box appears for guests but not foundry user

### ISSUE THREAD

**Issue by Naroek56** [League-of-Foundry-Developers/fvtt-module-polyglot#90] opened 2021-03-16 17:22 UTC
System information:
Windows 10
Foundry 0.7.9
System: Old-School Essentials 1.1.4
Polyglot 1.5.6.7

Description:
After starting my world as GM or as a player I cannot select the language for chat. I can still edit journal entries with languages and read translated chat from connected guests. Guests connected through browser can select the chat language. 

I have tried uninstalling Polyglot and deleting the Polyglot settings from my world. Neither changed the outcome.

Please help.

**Comment by mclemente** [comment] 2021-03-16 20:25
I believe you've selected a character as a GM. Anyone who has selected a character will only be able to select the languages that character knows, that's why Guests can speak on any language.
As a GM, right click your name on the Players bar > Player Configuration >Release any characters you have selected.

**Comment by Naroek56** [comment] 2021-03-16 22:46
I have no characters selected. Even if I select a character and speak as them in chat I don't see the language bar. 
![image](https://user-images.githubusercontent.com/49316726/111389780-75ddd780-86a9-11eb-9465-f5d94224d5a5.png)

**Comment by mclemente** [comment] 2021-03-17 03:53
Are there any errors on your console (F12)?

**Comment by Naroek56** [comment] 2021-03-17 12:15
I get this error: 
polyglot.js:201 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at PolyGlot.updateUserLanguages (polyglot.js:201)
    at PolyGlot.setCustomLanguages (polyglot.js:482)

**Comment by mclemente** [comment] 2021-03-17 15:22
Have you set any default or custom language? I might have a fix already, but I have to check if that's actually your issue or not.

**Comment by Naroek56** [comment] 2021-03-17 16:30
I have deleted my custom language. In the test world I have never set one. The default language has always been Common.

**Comment by mclemente** [comment] 2021-03-17 19:15
Reopening in case the update hasn't fixed this issue.

**Comment by Naroek56** [comment] 2021-03-17 22:14
I just updated it. Still not working unfortunately. Here the errors again:
![image](https://user-images.githubusercontent.com/49316726/111545512-14337100-876e-11eb-9733-ceb1cbed4c43.png)
![image](https://user-images.githubusercontent.com/49316726/111545545-21506000-876e-11eb-87a4-153151146ab6.png)

**Comment by mclemente** [comment] 2021-03-18 00:25
Could you zip your world folder and send it to me?

**Comment by Naroek56** [comment] 2021-03-18 20:54
[test2.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/6167144/test2.zip)
Here you go

**Comment by mclemente** [comment] 2021-03-18 22:21
Even with your world I can't reproduce it, the selector menu shows up as normal. I'm out of ideas here, have you tried reinstalling OSE?

**Comment by Naroek56** [comment] 2021-03-18 22:23
I have, and I just tried again, same difference. The only thing I haven't tried is reinstall Foundry.

**Comment by Naroek56** [comment] 2021-03-18 22:48
Okay, so, it's not technically fixed, but I found a workaround.
Here a brief explanation what happened:
1. A while ago I tried to add "Deepcommon" as custom language. Since I couldn't add it to my characters I deleted it later.
2. At some point the Language bar disappeared. 
3. I JUST put "Deepcommon" into the DEFAULT language bar. That fixed it, even though it does not show up in the language list since I didn't put it in custom languages. It also works with any other random string. However, as soon as I put a legit language into the custom language bar it breaks again.

**Comment by Naroek56** [comment] 2021-03-20 16:04
Quick update: 1.5.6.9 did NOT fix the issue. Having a random text as default language still works as workaround, but a normal language will break it again.

**Comment by Naroek56** [comment] 2021-03-21 20:44
Another update: Still not fixed in 1.5.6.10.

**Comment by mclemente** [comment] 2021-03-22 01:43
I really don't know how to fix this, so my updates probably won't fix it.
Do you know how to debug things using the console? Because there's no way for me to know how it's broken for you with what I have.

**Comment by Naroek56** [comment] 2021-03-22 10:52
Unfortunately I don't. 
The only thing I could make out so far is that PolyGlot.defaultLanguage apparently is "undefined" whenever I put in a legitimate default language. So I assume that the issue is somewhere in "static get defaultLanguage()", in that it somehow "undefines" the value whenever it confirms that it is an actual language. Maybe a dataformat issue?
I don't know enough about javascript to figure it out on my own.

**Closed** 2021-07-11 08:55 UTC
Labels: bug, can't reproduce, question
