### ISSUE TITLE
Foundry Version 9.255 PF2e 3.7.2.10819 - No Journal Support for Polyglot

### ISSUE THREAD

**Issue by jadrian2006** [League-of-Foundry-Developers/fvtt-module-polyglot#223] opened 2022-03-17 11:37 UTC
**Describe the bug**
Polyglot no longer is supported as journal entries after Foundy and/PF2e upgrades.
Had journal entries which were captured as infernal, they no longer are translated or displayed outside of normal text(common).

**To Reproduce**
Create Journal Entry - no options to show polyglot, and or define text as polyglot.

**Expected behavior**
Navigation Bar showing drop down for languages, and toggle polyglot on menu bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/10923732/158800615-3c2e9d92-e522-4a51-8166-8b55f2f693b1.png)

 - Game System and version Foundry 9 build 255, PF2e 3.7.2.10819
 - Polyglot Version  1.7.38
 - Are you using Babele? No

**Comment by jadrian2006** [comment] 2022-03-17 19:06
Thanks!

**Comment by mclemente** [comment] 2022-04-06 20:12
Hey, just getting back to know if the issue is resolved on your end so I can close this issue. It seems to work fine now on my end on PF2e 3.8.

**Comment by jadrian2006** [comment] 2022-04-06 20:13
It is, thank you for the follow up!


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Closed** 2022-04-06 20:45 UTC
Labels: bug
