### ISSUE TITLE
Warning about bad maxzones for Thorass Font

### ISSUE THREAD

**Issue by caewok** [League-of-Foundry-Developers/fvtt-module-polyglot#64] opened 2021-01-18 02:02 UTC
Foundry 0.7.9, dnd5e 1.2.0, Firefox 84.0.2, Mac OS X 10.15.7. I get this warning in the console when loading the polyglot module:

> downloadable font: maxp: Bad maxZones: 0 (font-family: "Thorass" style:normal weight:400 stretch:100 src index:0) source: https://[FOUNDRY SERVER URL]/modules/polyglot/fonts/Thorass.otf

Googling "bad maxzones" comes up with some discussions but no obvious culprit. I don't know if it is affecting the rendering. Maybe if I knew what language corresponds to the Thorass font, I could check.

**Comment by mclemente** [comment] 2021-02-15 21:45
According to this [StackOverflow post](https://magento.stackexchange.com/questions/80474/how-can-i-solve-font-downloadable-error-downloadable-font-os-2-bad-linegap), it might have been caused by the space between `font-family: '` or `src: url` on the .css file, which is... amusing.

**Comment by mclemente** [comment] 2021-02-24 06:52
If that was the cause, it was fixed on 1.5.5.1.

**Closed by mclemente** 2021-02-24 06:52 UTC
Labels: bug
