### ISSUE TITLE
System support for GURPS 4e -- Does not appear to work as per Closed Item #218

### ISSUE THREAD

**Issue by TheFabulousIronChef** [League-of-Foundry-Developers/fvtt-module-polyglot#229] opened 2022-04-13 23:02 UTC
**Describe the bug**
I cannot get the module to display text that shows it translated for the player who understands the language being used no matter what I do with any players on their character sheets. That is so even if I change the languages in the import file or change them from within Foundry.  

**To Reproduce**
This happens when I used custom languages or the standard with GURPS Game Aid. If I have an advantage on the Character sheet as Language (Ancient) or Language: Ancient, when I type a statement as the GM with "Ancient" selected as the language, no one can understand it, even those who speak Ancient as per their character sheets. Likewise, they do not have a drop-down list for anything other than common. The first screenshot is the GM view, the second screenshot is the player view. 

**Expected behavior**
It should translate the words spoken for the player who knows that language. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46587602/163283054-27109844-2c62-408d-94e6-c4387d653ea5.png)
![image](https://user-images.githubusercontent.com/46587602/163282990-64b9b9da-0e36-4922-966a-07533ed4d713.png)
![image](https://user-images.githubusercontent.com/46587602/163283453-4200a3f5-c194-4e7b-b310-371c2b3861cf.png)
![image](https://user-images.githubusercontent.com/46587602/163283485-00767c9a-21d9-4e28-bd22-40d86ebb1cad.png)
![image](https://user-images.githubusercontent.com/46587602/163283509-d0940359-75eb-4749-86b4-eafbac4e4b03.png)
![image](https://user-images.githubusercontent.com/46587602/163283524-b3fb96c8-f613-49df-b7f4-dd0768d49c98.png)

- Foundry v. 9.266
- GURPS Game Aid 0.13.14 
- Polyglot Version 1.7.38
- Are you using Babele? [**No**]

**Additional context**

**Comment by TheFabulousIronChef** [comment] 2022-04-13 23:03
Also, it's kind of strange that "Default Alphabet" and "Common" want a font, but I just left them as is and didn't change anything, and they display correctly. So that's not an issue, just a little odd that there is no ability to select "default" or something like that.

**Comment by TheFabulousIronChef** [comment] 2022-04-13 23:10
I also tried adding two advantages, one called "Ancient," and the other called "Language" and "Ancient" as the subcategory. Didn't make a difference; still doesn't work.  

![image](https://user-images.githubusercontent.com/46587602/163284334-a35b4145-e92f-4c78-81e3-f1e89dbf60a3.png)

**Comment by TheFabulousIronChef** [comment] 2022-04-14 11:39
I also tried putting Language (Ancient) in notes, as a skill, as equipment, etc. -- still doesn't work.

**Comment by mclemente** [comment] 2022-04-21 07:51
I forgot to reply to this, but I couldn't reproduce this. Setting an advantage like `Language (Ancient)` worked fine for me.

**Comment by TheFabulousIronChef** [comment] 2022-04-21 14:50
Apparently it does work if the advantage is "top level," but not if it is
in a container (folder). I believe Chris Normand (one of authors of GGA)
was going to submit a pull request or something for this.

**Comment by crnormand** [comment] 2022-04-21 14:58
Yes, I am working on one now.   I just needed to know if there was a "level" of comprehension that I should set, along with the list of known_languages and literate_languages (there is not).

The GURPS Game Aid can accept data from GCA4, GCA5 and GCS, and of course, each one indicates "languages" slightly differently, so the code is slightly more complex than a single regex, sadly.

**Comment by crnormand** [comment] 2022-04-22 20:57
Fixed with: https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/pull/234

**Closed** 2022-04-22 23:52 UTC
Labels: bug
